### ISSUE TITLE
Implement Database Model

### ISSUE THREAD

**Issue by Abhisheh** [mcgamer0070/AniMoCity#3]
Transform AniMoV6.png into a database. (ER-diagram in attachment)

![animov6](https://cloud.githubusercontent.com/assets/9843796/12478322/9ccb23c0-c034-11e5-8d27-53baad9d37da.png)

Edit:
Have to reimplement the Database anyway

**Comment by Abhisheh** [comment]
The model has been updated and the errors have been fixed. Additionally, Anime should now include pictures for the GUI.

![animov7](https://cloud.githubusercontent.com/assets/9843796/12913051/ba774a24-cf1c-11e5-82a0-3698546dc401.png)

**Comment by mcgamer0070** [comment]
Were is the source

**Comment by Abhisheh** [comment]
doesn't accept .rar or .dia
 look up your GMAIL

**Comment by mcgamer0070** [comment]
Implemented Database

**Comment by Abhisheh** [comment]
Finally.  Thanks.
